// tw-clone/components/common/input.tsx
import { ForwardedRef, forwardRef } from 'react';
import { twMerge } from 'tailwind-merge';

type Props = Omit<React.ComponentPropsWithRef<'input'>, 'type'> & {
  type: 'text' | 'password' | 'email' | 'search';
};

const Input = forwardRef(
  (props: Props, ref: ForwardedRef<HTMLInputElement>) => {
    const { className, ...rest } = props;
    return (
      <input
        ref={ref}
        className={twMerge(
          'h-11 w-full rounded-sm px-4 font-medium focus:outline-none',
          className,
        )}
        {...rest}
      />
    );
  },
);

Input.displayName = 'Input';
export default Input;

// spring-project/board-vue/src/shared/ui/Input.vue
<template>
  <input
      ref="inputRef"
      v-bind="attrs"
      :type="type"
      :class="['font-medium focus:outline-none', customClass]"
  />
</template>

<script lang="ts">
import { defineComponent, ref, computed, useAttrs } from 'vue';

export default defineComponent({
  name: 'Input',
  props: {
    type: {
      type: String as () => 'text' | 'password' | 'email' | 'search',
      required: true,
    },
    class: {
      type: String,
      default: '',
    },
  },
  setup(props) {
    const attrs = useAttrs();
    const inputRef = ref<HTMLInputElement | null>(null);
    const customClass = computed(() => (props.class ?? '') as string);

    return {
      inputRef,
      type: props.type,
      customClass,
      attrs,
    };
  },
});
</script>
